### ISSUE TITLE
Include Yggdrasil dependency

### ISSUE THREAD

**Issue by andrewazores** [FRC3161/Astrilde2022#2]
For reference:

https://github.com/FRC3161/WoodieFlowers2020/blob/master/build.gradle

https://github.com/FRC3161/Heimdall2019/blob/master/build.gradle

[Yggdrasil](https://github.com/frc3161/yggdrasil) can be added as a Maven dependency via [jitpack](https://jitpack.io/#frc3161/yggdrasil).

It's basically just two lines to do this - one to add jitpack as a repository where Yggdrasil can be found, and one to define the Yggdrasil dependency.

**Comment by bartek717** [comment]
is this still the correct import? "com.github.FRC3161:Yggdrasil:e04c00a361"

**Comment by andrewazores** [comment]
That import is using a commit hash instead of a tagged version.
